### ISSUE TITLE
Criar protótipos das páginas do site

### ISSUE THREAD

**Issue by vpaesi** [lucasdemattos8/project-ponte_de_geracoes#1]
# Criar o prorótipo das páginas do site:

- [x] - Home Page
- [x] - Cadastro
- [x] - Edição de cadastro
- [x] - Login
- [x] - Cadastrados

#### Site para criação do protótipo: https://moqups.com/

**Comment by vpaesi** [comment]
Criadas as 5 páginas. **Aguardando aprovação da dupla**. @lucasdemattos8 

[Acessar protótipo](https://app.moqups.com/HgZ0BGHfnDW8lyJBFuK45SWQTzOWb3HZ/view/page/a153d733d)

Print dos protótipos no Moqup das páginas:
- Home Page:
![Print da Home Page](https://github.com/user-attachments/assets/e800435d-cc00-4032-85f8-3038af25e7f5)

- Login
![image](https://github.com/user-attachments/assets/d6137981-ca6d-4303-91aa-40ddecd73cbf)

- Cadastro
![image](https://github.com/user-attachments/assets/f7d46ce2-c25d-4e69-991d-469bce92ceaa)

- Editar Cadastro
![image](https://github.com/user-attachments/assets/a69d428c-586b-48a0-809b-4ea6c3257aa2)

- Cadastrados
![image](https://github.com/user-attachments/assets/3de8270c-cf7f-42d7-8932-72cf651d6058)

**Comment by lucasdemattos8** [comment]
Boa noite, ótimos protótipos. Estão aprovados sim, vou alinhar demais funcionalidades amanhã durante a daily
