### ISSUE TITLE
Criação de Modelos básicos do sistema (Entidades) e repositórios

### ISSUE THREAD

**Issue by lucasdemattos8** [lucasdemattos8/project-ponte_de_geracoes#13]
### **💬 Descrição:**

Criar as entidades **`Helper`** e **`Assisted`**, representando dois tipos de usuários no sistema. A entidade **`Helper`** conterá informações sobre os usuários que oferecem ajuda, enquanto a entidade **`Assisted`** representará os usuários que precisam de ajuda. Ambas as entidades terão atributos semelhantes, com a diferença principal de que o **`Helper`** tem um campo **`skills`** e o **`Assisted`** terá um campo **`needs`**.

### ❗ AVISO:
- **Implementar o modelo básico (SEM RELACIONAMENTOS), será aberto outro issue para os relacionamentos de entidades (modelos).**

### **📋 Tarefas:**

- - [x] Criar a classe **`Helper`** com os seguintes atributos:
  - `id` (Long) - Chave primária.
  - `name` (String) - Nome completo do usuário.
  - `cpf` (String) - CPF do usuário.
  - `age` (Integer) - Idade do usuário.
  - `email` (String) - E-mail do usuário.
  - `phone` (String) - Telefone do usuário.
  - `address` (String) - Endereço do usuário.
  - `skills` (String) - Habilidades do usuário para oferecer ajuda.

- - [x] Criar a classe **`Assisted`** com os seguintes atributos:
  - `id` (Long) - Chave primária.
  - `name` (String) - Nome completo do usuário.
  - `cpf` (String) - CPF do usuário.
  - `age` (Integer) - Idade do usuário.
  - `email` (String) - E-mail do usuário.
  - `phone` (String) - Telefone do usuário.
  - `address` (String) - Endereço do usuário.
  - `needs` (String) - Necessidades do usuário que precisa de ajuda.

- - [x] Criar um **repositório** básico para cada entidade, utilizando `JpaRepository`, para permitir operações CRUD.

### **⚠ Critérios de Aceitação:**

  - - [x] Entidades **`Helper`** e **`Assisted`** criadas corretamente com as anotações JPA.
  - - [x] As entidades estão configuradas com os atributos necessários.
- - [x] Repositórios criados para as entidades, permitindo operações CRUD básicas.
- - [x] Aplicação compila sem erros e está pronta para testar operações de banco de dados.

### **📎 Anexos e prints:**

Um exemplo de código das entidades:

```java
@Entity
public class Helper {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;        // Nome completo do usuário
    private String cpf;         // CPF do usuário
    private Integer age;        // Idade do usuário
    private String email;       // E-mail do usuário
    private String phone;       // Telefone do usuário
    private String address;     // Endereço do usuário
    private String skills;      // Habilidades do usuário
}

@Entity
public class Assisted {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;        // Nome completo do usuário
    private String cpf;         // CPF do usuário
    private Integer age;        // Idade do usuário
    private String email;       // E-mail do usuário
    private String phone;       // Telefone do usuário
    private String address;     // Endereço do usuário
    private String needs;       // Necessidades do usuário
}
```

**Comment by lucasdemattos8** [comment]
### Classe base da Entidade de Ajudante criada

Seguindo como base alguns atributos combinados, foi criado a classe base de Entidade Helper

![image](https://github.com/user-attachments/assets/3059d207-ab64-41ff-a058-8e5f71f2ec76)

**Comment by lucasdemattos8** [comment]
Acho que em um segundo momento nos podemos criar uma entidade para o endereço, aonde contem os campos de:

```java
@Entity
public class Address {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String street;
    private String city;
    private String state;
    private String postalCode;

    // Getters, Setters, Constructors
}

```

aonde nós nos alinhamos com a questão do front-end de cadastro

**Comment by vpaesi** [comment]
Classe base da Entidade de Ajudado criada
Seguindo como base alguns atributos combinados, foi criado a classe base de Entidade Assisted

![image](https://github.com/user-attachments/assets/3d1e65df-51a7-4cd6-aa1c-5b538c05ebf2)
